## 预定义异常


### Exception
* `Exception` 是 __所有异常的基类__

* 类摘要
```php
Exception {
    /* 属性 */
    protected string $message ;
    protected int $code ;
    protected string $file ;
    protected int $line ;

    /* 方法 */
    public __construct ([ string $message = "" [, int $code = 0 [, Throwable $previous = NULL ]]] )
    final public string getMessage ( void )
    final public Throwable getPrevious ( void )
    final public int getCode ( void )
    final public string getFile ( void )
    final public int getLine ( void )
    final public array getTrace ( void )
    final public string getTraceAsString ( void )
    public string __toString ( void )
    final private void __clone ( void )
}
```


### ErrorException
* `ErrorException` 错误异常

* 类摘要
```php
ErrorException extends Exception {
    /* 属性 */
    protected int $severity ;

    /* 方法 */
    public __construct ([ string $message = "" [, int $code = 0 [, int $severity = E_ERROR [, string $filename = __FILE__ [, int $lineno = __LINE__ [, Exception $previous = NULL ]]]]]] )
    final public int getSeverity ( void )

    /* 继承的方法 */
    final public string Exception::getMessage ( void )
    final public Throwable Exception::getPrevious ( void )
    final public int Exception::getCode ( void )
    final public string Exception::getFile ( void )
    final public int Exception::getLine ( void )
    final public array Exception::getTrace ( void )
    final public string Exception::getTraceAsString ( void )
    public string Exception::__toString ( void )
    final private void Exception::__clone ( void )
}
```

* 使用 `set_error_handler()` 函数将错误信息托管至 `ErrorException`
```php
<?php
function exception_error_handler($errno, $errstr, $errfile, $errline ) {
    throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
}
set_error_handler("exception_error_handler");

/* Trigger exception */
strpos();

/**
PHP Fatal error:  Uncaught ErrorException: strpos() expects at least 2 parameters, 0 given in /mnt/d/codes/php_manual/index.php:10
Stack trace:
#0 [internal function]: exception_error_handler(2, 'strpos() expect...', '/mnt/d/codes/ph...', 10, Array)
#1 /mnt/d/codes/php_manual/index.php(10): strpos()
#2 {main}
  thrown in /mnt/d/codes/php_manual/index.php on line 10
  */
```


### SPL 异常处理
* SPL Exceptions Class Tree
```php
* LogicException (extends Exception)
    * BadFunctionCallException
        * BadMethodCallException

    * DomainException
    * InvalidArgumentException
    * LengthException
    * OutOfRangeException

* RuntimeException (extends Exception)
    * OutOfBoundsException
    * OverflowException
    * RangeException
    * UnderflowException
    * UnexpectedValueException
```
